project_id = "nzrfekddelcojckpauqi"

[functions.ssh-command]
verify_jwt = false

[functions.stream-proxy]
verify_jwt = false

[functions.deploy-proxy-config]
verify_jwt = false

[functions.xtream-api]
verify_jwt = false

[functions.m3u-playlist]
verify_jwt = false

[functions.epg-import]
verify_jwt = false

[functions.m3u-import]
verify_jwt = false

[functions.backend-sync]
verify_jwt = false

[functions.update-webhook]
verify_jwt = false

[functions.lb-deploy]
verify_jwt = false

[functions.stalker-portal]
verify_jwt = false

[functions.ip-geolocation]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false
